flagpolejs/flagpole

src/Browser.ts
src/scenario.ts
src/suite.ts

We have added launch options so that we can run our new ui tests in docker.

A3 - adding launch options for puppeteer

---

src/assertioncontext.ts
tests/src/smoke.ts

findHavingText and findAllHavingText

---

flagpole.json
src/browsercontrol.ts
tests/src/browser/setBasicAuth.ts
tests/src/cookies.ts

The issue:
- setBasicAuth works on .html tests, not on .browser tests
Adding this to browser control fixes the issue.
Added new setBasicAuth test to prove, and begun debugging setCookies .browser issue...

Set basic auth

---

docs/cli.md

Update CLI docs for multiple suite execution

---

src/scenario.ts

make puppeteer page errors an optional failure

---

src/assertioncontext.ts

[breaking change for node < 15](https://github.com/flagpolejs/flagpole/commit/8f4f7248ea18f632fa550dc70a9ef5abddf2de40#diff-beed22ee3e6613850742ebe48f675fb294298100d4ac221ea33fb570b645663c)
Fixes #76

Rollback to use bluebird

---

flagpole.json
package-lock.json
package.json
src/assertioncontext.ts
src/interfaces.ts
src/puppeteer/browserresponse.ts
tests/src/browser/google.ts
tests/src/waitForHavingText.ts
yarn.lock

The issue with this method is that it only looks at the first element that meets the selector. If we're going to "wait for ANY element that has this text" and not just the first one, we need to implement a loop of sorts to consider ALL elements that match the given selector. 
Fixes #83

waitForHavingText

---

flagpole.json
package-lock.json
package.json
src/puppeteer/browsercontrol.ts
src/suitetaskmanager.ts
tests/src/maxListener.ts
yarn.lock

- `setConcurrencyLimit(5)` will wait for the _first response_ of a browser to settle, before launching the next batch of scenarios
- an error is shown when we launch more than 10 browser scenarios:
```
(node:26511) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 exit listeners added to [process]. Use emitter.setMaxListeners() to increase limit
(node:26511) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 SIGINT listeners added to [process]. Use emitter.setMaxListeners() to increase limit
(node:26511) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 SIGTERM listeners added to [process]. Use emitter.setMaxListeners() to increase limit
(node:26511) MaxListenersExceededWarning: Possible EventEmitter memory leak …
```

(fix): setConcurrencyLimit and MaxListenersExceededWarning

---

flagpole.json
src/flagpoleexecution.ts
src/logging/flagpolereport.ts
tests/src/simple.ts

I need help testing this and welcome any changes 👍 
Fixes #97

XML output option

---

.gitignore
docs/cli.md
package.json
src/cli/testrunner.ts
src/cli/web/report.xml
src/logging/flagpolereport.ts

- Replace conditional with switch statement
- Write the XML all at once with a unique filename from the test runner instead
- Sanitize forbidden XML characters
- Take `time` off of the scenarios, it is not accurate

XML improvements

---

flagpole.json
src/assertion.ts
tests/src/equality.ts

Improve test report for expected values

---

src/logging/flagpolereport.ts

Better test reporting with finer details on subscenario headings

XML Subscenarios

---

flagpole.json
src/assertion.ts
tests/src/every.ts

stringify expected value in every

---

docs/setup.md

A short blurb on setting up and hooking into Appium

Added information on setting up appium

---

src/appium/appiumresponse.ts

Added method to find all instances of an element on a page

Appium findAll

---

docs/assertion-context.md

selectOption

---

src/appium/appiumelement.ts

Using protected method on AppiumElement

Added ability to get text of an element

---

src/appium/appiumelement.ts

Can now enter text into an input field.

Appium enter, clear, clear then enter text

---

src/appium/appium-helpers.ts
src/appium/appiumelement.ts
src/appium/appiumresponse.ts
src/assertioncontext.ts
src/helpers.ts
src/interfaces.ts
src/scenario.ts

Appium aliases to properties

---

src/appium/appiumelement.ts
src/appium/appiumresponse.ts

Appium is visible

---

package-lock.json
src/appium/appiumelement.ts
src/appium/appiumresponse.ts
src/value.ts

Added get tag name and changed up how constructor is accessed.

Appium get tag name

---

src/appium/appium-helpers.ts
src/appium/appiumresponse.ts
src/interfaces.ts
src/response.ts

Added ability to run touch actions press, longpress, multitap, swipe/scroll. Does not do pinch or zoom; only supports using 1 finger at this time.

Appium touch

---

src/appium/appiumresponse.ts

Please look at this change to make sure it is what we want to do, it replaces the first `/` with an `@` and then splits on the `@` to make sure we get the xpath now

made adjustments to fix xpath

---

src/appium/appiumresponse.ts

Split without replace

---

src/appium/appium-helpers.ts
src/appium/appiumresponse.ts
src/interfaces.ts
src/scenario.ts
src/suite.ts

Adds ability to set geolocation when spinning up an Appium scenario. Also adds the ability to get geolocation coordinates.

Appium set geolocation

---

src/appium/appiumresponse.ts

Allows putting the app in the background

Appium background app

---

docs/ivalue.md
src/appium/appiumelement.ts
src/interfaces.ts
src/value.ts

Get dimensions and some points for an element

Appium get element dimensions

---

src/appium/appium-helpers.ts
src/appium/appiumelement.ts
src/appium/appiumresponse.ts

Now able to find child elements of AppiumElement objects

Added ability to find child elements

---

docs/appiumresponse.md
docs/assertion-context.md
docs/ivalue.md
docs/setup.md
tests/src/appium/smoke.ts

Documentation and tests for "Full Functionality" features.

Appium docs full functionality
